author: Seunghyun Yang
author_url: https://github.com/SHcommit
github_url: https://github.com/SHcommit/UIKitDeepDive/CustomCollectionView/CategoryPageView
theme: apple
module_version: 1.0.0
xcodebuild_arguments:
  - -scheme
  - CategoryPageView
hide_documentation_coverage: true
output: docs/documentation

# 검색 활성
disable_search: false

source:
  - Source
include:
  - '**/*.swift'
